#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'thrshMsg'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 6

# The Active Message type associated with this message.
AM_TYPE = 9

class thrshMsg(tinyos.message.Message.Message):
    # Create a new thrshMsg of size 6.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=6):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <thrshMsg> \n"
        try:
            s += "  [thresh_type=0x%x]\n" % (self.get_thresh_type())
        except:
            pass
        try:
            s += "  [thesh_l=0x%x]\n" % (self.get_thesh_l())
        except:
            pass
        try:
            s += "  [thesh_h=0x%x]\n" % (self.get_thesh_h())
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: thresh_type
    #   Field type: int
    #   Offset (bits): 0
    #   Size (bits): 16
    #

    #
    # Return whether the field 'thresh_type' is signed (False).
    #
    def isSigned_thresh_type(self):
        return False
    
    #
    # Return whether the field 'thresh_type' is an array (False).
    #
    def isArray_thresh_type(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'thresh_type'
    #
    def offset_thresh_type(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'thresh_type'
    #
    def offsetBits_thresh_type(self):
        return 0
    
    #
    # Return the value (as a int) of the field 'thresh_type'
    #
    def get_thresh_type(self):
        return self.getUIntElement(self.offsetBits_thresh_type(), 16, 1)
    
    #
    # Set the value of the field 'thresh_type'
    #
    def set_thresh_type(self, value):
        self.setUIntElement(self.offsetBits_thresh_type(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'thresh_type'
    #
    def size_thresh_type(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'thresh_type'
    #
    def sizeBits_thresh_type(self):
        return 16
    
    #
    # Accessor methods for field: thesh_l
    #   Field type: int
    #   Offset (bits): 16
    #   Size (bits): 16
    #

    #
    # Return whether the field 'thesh_l' is signed (False).
    #
    def isSigned_thesh_l(self):
        return False
    
    #
    # Return whether the field 'thesh_l' is an array (False).
    #
    def isArray_thesh_l(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'thesh_l'
    #
    def offset_thesh_l(self):
        return (16 / 8)
    
    #
    # Return the offset (in bits) of the field 'thesh_l'
    #
    def offsetBits_thesh_l(self):
        return 16
    
    #
    # Return the value (as a int) of the field 'thesh_l'
    #
    def get_thesh_l(self):
        return self.getUIntElement(self.offsetBits_thesh_l(), 16, 1)
    
    #
    # Set the value of the field 'thesh_l'
    #
    def set_thesh_l(self, value):
        self.setUIntElement(self.offsetBits_thesh_l(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'thesh_l'
    #
    def size_thesh_l(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'thesh_l'
    #
    def sizeBits_thesh_l(self):
        return 16
    
    #
    # Accessor methods for field: thesh_h
    #   Field type: int
    #   Offset (bits): 32
    #   Size (bits): 16
    #

    #
    # Return whether the field 'thesh_h' is signed (False).
    #
    def isSigned_thesh_h(self):
        return False
    
    #
    # Return whether the field 'thesh_h' is an array (False).
    #
    def isArray_thesh_h(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'thesh_h'
    #
    def offset_thesh_h(self):
        return (32 / 8)
    
    #
    # Return the offset (in bits) of the field 'thesh_h'
    #
    def offsetBits_thesh_h(self):
        return 32
    
    #
    # Return the value (as a int) of the field 'thesh_h'
    #
    def get_thesh_h(self):
        return self.getUIntElement(self.offsetBits_thesh_h(), 16, 1)
    
    #
    # Set the value of the field 'thesh_h'
    #
    def set_thesh_h(self, value):
        self.setUIntElement(self.offsetBits_thesh_h(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'thesh_h'
    #
    def size_thesh_h(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'thesh_h'
    #
    def sizeBits_thesh_h(self):
        return 16
    
